delimiter //
/** テーブル作成 **/
CREATE TABLE location_stocks_history(
	history_record_id			int						NOT NULL AUTO_INCREMENT				COMMENT '履歴ID'
,	history_record_date			datetime				NOT NULL DEFAULT CURRENT_TIMESTAMP	COMMENT '履歴追加日'
,	history_record_divide		ENUM('I','U','D')		NOT NULL							COMMENT '履歴区分 I:登録 U:更新 D:削除'
,	DET_ID						int UNSIGNED			NOT NULL							COMMENT '在庫管理ID'
,	NNSICD						varchar(10)				NOT NULL							COMMENT '荷主コード'
,	NNSINM						varchar(50)				NOT NULL							COMMENT '荷主名称'
,	JGSCD						varchar(10)				NOT NULL							COMMENT '事業所コード'
,	JGSNM						varchar(50)				NOT NULL							COMMENT '事業所名称'
,	SRRNO						varchar(2)				DEFAULT NULL						COMMENT '未合区分'
,	RTNO						varchar(20)				NOT NULL							COMMENT 'ロット'
,	KANRIK						varchar(2)				NOT NULL							COMMENT '管理区分'
,	SYUKAK						varchar(2)				NOT NULL							COMMENT '出荷区分'
,	KOUJOK						varchar(3)				NOT NULL							COMMENT '工場区分'
,	SNTCD						varchar(10)				NOT NULL							COMMENT 'センターコード'
,	SNTNM						varchar(50)				NOT NULL							COMMENT 'センター名称'
,	SHCD						varchar(10)				NOT NULL							COMMENT '商品コード'
,	SHNM						varchar(50)				DEFAULT NULL						COMMENT '製品名称'
,	DNRK						varchar(20)				DEFAULT NULL						COMMENT '電略'
,	SHNKKKMEI_KS				varchar(20)				DEFAULT NULL						COMMENT '規格ケース'
,	SR1RS						int						NOT NULL DEFAULT 0					COMMENT '入目１'
,	PL							int						NOT NULL DEFAULT 0					COMMENT 'パレット積数'
,	KSNJ						datetime				DEFAULT NULL						COMMENT '更新日'
,	ZNJTZIKSURU1				int						NOT NULL DEFAULT 0					COMMENT '会計前日在庫ケース'
,	ZNJTZIKSURU3				int						NOT NULL DEFAULT 0					COMMENT '会計前日在庫バラ'
,	NUKSURU1					int						NOT NULL DEFAULT 0					COMMENT '会計入庫ケース'
,	NUKSURU3					int						NOT NULL DEFAULT 0					COMMENT '会計入庫バラ'
,	SKSURU1						int						NOT NULL DEFAULT 0					COMMENT '会計出庫ケース'
,	SKSURU3						int						NOT NULL DEFAULT 0					COMMENT '会計出庫バラ'
,	TUJTZIKSURU1				int						NOT NULL DEFAULT 0					COMMENT '会計当日在庫ケース'
,	TUJTZIKSURU3				int						NOT NULL DEFAULT 0					COMMENT '会計当日在庫バラ'
,	SKYTI1SURU1					int						NOT NULL DEFAULT 0					COMMENT '会計出庫予定１ケース'
,	SKYTI1SURU3					int						NOT NULL DEFAULT 0					COMMENT '会計出庫予定１バラ'
,	TRNJ						datetime				DEFAULT NULL						COMMENT 'DB取込時間'
,	PYTStocktakingDate			date					NOT NULL							COMMENT '棚卸日YYYYMMDD'
,	PYTexStocks1				int						DEFAULT NULL						COMMENT '前日在庫ケース'
,	PYTexStocks3				int						DEFAULT NULL						COMMENT '前日在庫バラ'
,	PYTPicking1					int						DEFAULT NULL						COMMENT '出庫ケース'
,	PYTPicking3					int						DEFAULT NULL						COMMENT '出庫バラ'
,	PYTstock1					int						DEFAULT NULL						COMMENT '在庫ケース'
,	PYTstock3					int						DEFAULT NULL						COMMENT '在庫バラ'
,	PYTPLQ						int						DEFAULT NULL						COMMENT 'PL枚数'
,	PYTPLP						int						DEFAULT NULL						COMMENT 'PL端数'
,	JitsuCase					int						NOT NULL DEFAULT 0					COMMENT '実ケース'
,	JitsuBara					int						NOT NULL DEFAULT 0					COMMENT '実バラ'
,	ReportComment				varchar(255)			DEFAULT NULL						COMMENT '報告者コメント'
,	Reporter					varchar(20)				DEFAULT NULL						COMMENT '報告者'
,	ReportCorpName				varchar(60)				DEFAULT NULL						COMMENT '報告会社名'
,	ReportDatetime				datetime				DEFAULT NULL						COMMENT '報告日時'
,	ReviewComment				varchar(255)			DEFAULT NULL						COMMENT '確認者コメント'
,	ReviewerID					varchar(20)				DEFAULT NULL						COMMENT '確認者'
,	ReviewDatetime				datetime				DEFAULT NULL						COMMENT '確認日時'
,	AuthorizerComment			varchar(255)			DEFAULT NULL						COMMENT '承認者名コメント'
,	AuthorizerID				varchar(20)				DEFAULT NULL						COMMENT '承認者'
,	AuthorizerDatetime			datetime				DEFAULT NULL						COMMENT '承認日時'
,	Status						tinyint					NOT NULL DEFAULT 0					COMMENT 'ステータス'
,	AddFlag						tinyint					NOT NULL DEFAULT 0					COMMENT '追加判定フラグ'
,	PRIMARY KEY (history_record_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='在庫の履歴保持を行う)';//

delimiter ;
