delimiter //
/** テーブル作成 **/
CREATE TABLE shipment_provisional_details_history(
	history_record_id			int						NOT NULL AUTO_INCREMENT				COMMENT '履歴ID'
,	history_record_date			datetime				NOT NULL DEFAULT CURRENT_TIMESTAMP	COMMENT '履歴追加日'
,	history_record_divide		ENUM('I','U','D')		NOT NULL							COMMENT '履歴区分 I:登録 U:更新 D:削除'
,	ID							int						NOT NULL							COMMENT '仮出荷ID'
,	JGSCD						varchar(10)				NOT NULL							COMMENT '事業所コード'
,	JGSNM						varchar(50)				NOT NULL							COMMENT '事業所名称'
,	SNTCD						varchar(10)				NOT NULL							COMMENT 'センターコード'
,	SNTNM						varchar(50)				NOT NULL							COMMENT 'センター名称'
,	DENGNO						int						NOT NULL							COMMENT '伝票行番号'
,	SHCD						varchar(10)				NOT NULL							COMMENT '商品コード'
,	SHNM						varchar(50)				DEFAULT NULL						COMMENT '製品名称'
,	BTRUCD						varchar(10)				DEFAULT NULL						COMMENT '物流コード'
,	TITSHNCD					varchar(10)				DEFAULT NULL						COMMENT '統一商品コード'
,	GS1CD						varchar(30)				DEFAULT NULL						COMMENT 'GS1コード'
,	JANCD						varchar(30)				DEFAULT NULL						COMMENT 'JANコード'
,	ITFCD						varchar(30)				DEFAULT NULL						COMMENT 'ITFコード'
,	SPDCD						varchar(30)				DEFAULT NULL						COMMENT 'SPDコード'
,	DNRK						varchar(20)				DEFAULT NULL						COMMENT '電略'
,	SEKKBN						varchar(10)				DEFAULT NULL						COMMENT '請求区分'
,	GKYKGKBTKBN					tinyint					NOT NULL DEFAULT 0					COMMENT '劇薬劇物区分'
,	YNUHNFRG					tinyint					NOT NULL DEFAULT 0					COMMENT '輸入品フラグ'
,	YSTHNFRG					tinyint					NOT NULL DEFAULT 0					COMMENT '輸出品フラグ'
,	KTCD						varchar(10)				DEFAULT NULL						COMMENT '型コード'
,	BUNRUI						varchar(10)				DEFAULT NULL						COMMENT '商品分類'
,	SHNKKKMEI					varchar(20)				DEFAULT NULL						COMMENT '規格'
,	JR_KS						decimal(10,3)			NOT NULL DEFAULT 0					COMMENT '重量_ケース'
,	JR_CU						decimal(10,3)			NOT NULL DEFAULT 0					COMMENT '重量_中間'
,	JR_BR						decimal(10,3)			NOT NULL DEFAULT 0					COMMENT '重量_バラ'
,	SHTT_KS						int						NOT NULL DEFAULT 0					COMMENT '商品縦_ケース'
,	SHYK_KS						int						NOT NULL DEFAULT 0					COMMENT '商品横_ケース'
,	SHTKS_KS					int						NOT NULL DEFAULT 0					COMMENT '商品高さ_ケース'
,	SHTT_CU						int						NOT NULL DEFAULT 0					COMMENT '商品縦_中間'
,	SHYK_CU						int						NOT NULL DEFAULT 0					COMMENT '商品横_中間'
,	SHTKS_CU					int						NOT NULL DEFAULT 0					COMMENT '商品高さ_中間'
,	SHTT_BR						int						NOT NULL DEFAULT 0					COMMENT '商品縦_バラ'
,	SHYK_BR						int						NOT NULL DEFAULT 0					COMMENT '商品横_バラ'
,	SHTKS_BR					int						NOT NULL DEFAULT 0					COMMENT '商品高さ_バラ'
,	RTNO						varchar(20)				NOT NULL							COMMENT 'ロット'
,	RTNOSTIFLG					varchar(2)				DEFAULT NULL						COMMENT 'ロット指定フラグ'
,	SR1RS						int						NOT NULL DEFAULT 0					COMMENT 'ケース入目'
,	SR2RS						int						NOT NULL DEFAULT 0					COMMENT '中間入目'
,	SR3RS						int						NOT NULL DEFAULT 0					COMMENT 'バラ入目'
,	JTIRM						int						NOT NULL DEFAULT 0					COMMENT '実入目'
,	PL							int						NOT NULL DEFAULT 0					COMMENT 'パレット積付数'
,	JCSR1						int						NOT NULL DEFAULT 0					COMMENT '受注数量ケース'
,	JCSR2						int						NOT NULL DEFAULT 0					COMMENT '受注数量中間'
,	JCSR3						int						NOT NULL DEFAULT 0					COMMENT '受注数量バラ'
,	JCSSR						int						NOT NULL DEFAULT 0					COMMENT '受注数量総バラ'
,	JCSJR						decimal(10,3)			NOT NULL DEFAULT 0					COMMENT '受注総重量'
,	KHKBN						tinyint					NOT NULL DEFAULT 0					COMMENT '梱端区分'
,	KKTSR1						int						NOT NULL DEFAULT 0					COMMENT 'ケース数量'
,	KKTSR2						int						NOT NULL DEFAULT 0					COMMENT '中間数量'
,	KKTSR3						int						NOT NULL DEFAULT 0					COMMENT 'バラ数量'
,	KKTSSR						int						NOT NULL DEFAULT 0					COMMENT '総バラ数量'
,	WGT							decimal(10,3)			NOT NULL DEFAULT 0					COMMENT '総重量'
,	LOTK						varchar(2)				NOT NULL							COMMENT '管理区分'
,	LOTS						varchar(2)				NOT NULL							COMMENT '出荷区分'
,	FCKBNKK						varchar(3)				NOT NULL							COMMENT '工場コード'
,	TRKMJ						datetime				NOT NULL DEFAULT CURRENT_TIMESTAMP	COMMENT 'ＤＢ取込時間'
,	PRIMARY KEY (history_record_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='仮出荷BODYの履歴保持を行う)';//

delimiter ;
