DROP PROCEDURE IF EXISTS pyt_p_999040;
delimiter //

CREATE PROCEDURE pyt_p_999040(
	IN p_JGSCD 		varchar(10)
,	IN p_TMCPTNCD 	varchar(10)
,	IN p_CKCPTNCD 	varchar(10)
,	IN p_UNSKSPTNCD varchar(10)
)
BEGIN    

	SELECT
		RT.root_id
	,	RT.JGSCD
	,	JGS.JGSNM
    ,	RT.TMCPTNCD
    ,	CONCAT(IFNULL(PN1.PTNCDNM1,''),IF(PN1.PTNCDNM2 IS NULL, '', ' '),IFNULL(PN1.PTNCDNM2,'')) AS TMCPTNNM
    ,	PN1.PTNCDJUSYO AS TMCJUSYO
    ,	RT.CKCPTNCD
    ,	CONCAT(IFNULL(PN2.PTNCDNM1,''),IF(PN2.PTNCDNM2 IS NULL, '', ' '),IFNULL(PN2.PTNCDNM2,'')) AS CKCPTNNM
    ,	PN2.PTNCDJUSYO AS CKCJUSYO
    ,	RT.UNSKSPTNCD
    ,	CONCAT(IFNULL(PN3.PTNCDNM1,''),IF(PN3.PTNCDNM2 IS NULL, '', ' '),IFNULL(PN3.PTNCDNM2,'')) AS UNSKSPTNNM
    ,	RT.del_flag
    FROM pyt_m_root AS RT
    LEFT JOIN pyt_m_jigyosho AS JGS
		ON RT.JGSCD = JGS.JGSCD
    LEFT JOIN pyt_m_partners AS PN1
		ON RT.TMCPTNCD = PN1.PTNCD
	LEFT JOIN pyt_m_partners AS PN2
		ON RT.CKCPTNCD = PN2.PTNCD
	LEFT JOIN pyt_m_partners AS PN3
		ON RT.UNSKSPTNCD = PN3.PTNCD
    WHERE (p_JGSCD IS NULL OR RT.JGSCD = p_JGSCD)
    AND (p_TMCPTNCD IS NULL OR RT.TMCPTNCD = p_TMCPTNCD)
    AND (p_CKCPTNCD IS NULL OR RT.CKCPTNCD = p_CKCPTNCD)
    AND (p_UNSKSPTNCD IS NULL OR RT.UNSKSPTNCD = p_UNSKSPTNCD)
    ORDER BY RT.JGSCD, RT.TMCPTNCD, RT.CKCPTNCD, RT.UNSKSPTNCD;

END//

delimiter ;