DROP PROCEDURE IF EXISTS pyt_p_999040_csv;
delimiter //


CREATE PROCEDURE pyt_p_999040_csv(
	IN p_JGSCD 		varchar(10)
,	IN p_TMCPTNCD 	varchar(10)
,	IN p_CKCPTNCD 	varchar(10)
,	IN p_UNSKSPTNCD varchar(10)
)
BEGIN    

	SELECT
		RT.JGSCD AS '事業所コード'
	,	JGS.JGSNM AS '事業所名'
    ,	RT.TMCPTNCD AS '積地PTコード'
    ,	CONCAT(IFNULL(PN1.PTNCDNM1,''),IF(PN1.PTNCDNM2 IS NULL, '', ' '),IFNULL(PN1.PTNCDNM2,'')) AS '積地PT名'
    ,	PN1.PTNCDJUSYO AS '積地PT住所'
    ,	RT.CKCPTNCD AS '着地PTコード'
    ,	CONCAT(IFNULL(PN2.PTNCDNM1,''),IF(PN2.PTNCDNM2 IS NULL, '', ' '),IFNULL(PN2.PTNCDNM2,'')) AS '着地PT名'
    ,	PN2.PTNCDJUSYO AS '着地PT住所'
    ,	RT.UNSKSPTNCD AS '運送会社PTコード'
    ,	CONCAT(IFNULL(PN3.PTNCDNM1,''),IF(PN3.PTNCDNM2 IS NULL, '', ' '),IFNULL(PN3.PTNCDNM2,'')) AS '運送会社PT名'
    ,	RT.del_flag AS '削除フラグ'
    FROM pyt_m_root AS RT
    LEFT JOIN pyt_m_jigyosho AS JGS
		ON RT.JGSCD = JGS.JGSCD
    LEFT JOIN pyt_m_partners AS PN1
		ON RT.TMCPTNCD = PN1.PTNCD
	LEFT JOIN pyt_m_partners AS PN2
		ON RT.CKCPTNCD = PN2.PTNCD
	LEFT JOIN pyt_m_partners AS PN3
		ON RT.UNSKSPTNCD = PN3.PTNCD
    WHERE (p_JGSCD IS NULL OR RT.JGSCD = p_JGSCD)
    AND (p_TMCPTNCD IS NULL OR RT.TMCPTNCD = p_TMCPTNCD)
    AND (p_CKCPTNCD IS NULL OR RT.CKCPTNCD = p_CKCPTNCD)
    AND (p_UNSKSPTNCD IS NULL OR RT.UNSKSPTNCD = p_UNSKSPTNCD)
    ORDER BY RT.JGSCD, RT.TMCPTNCD, RT.CKCPTNCD, RT.UNSKSPTNCD;

END//

delimiter ;