    <script src="<?=JS_DIR?>/common/const.js?ver=<?=date('ymdHis')?>"></script>
    <script src="<?=JS_DIR?>/include/jquery.min.js"></script>
    <script src="<?=JS_DIR?>/include/jquery.easing.min.js"></script>
    <script src="<?=JS_DIR?>/include/jquery-ui.js"></script>
    <script src="<?=JS_DIR?>/include/jquery.ui.datepicker-ja.min.js"></script>
    <script src="<?=JS_DIR?>/include/jquery.alerts.js"></script>
    <script src="<?=JS_DIR?>/include/jquery.validationEngine.js?ver=<?=date('ymdHis')?>"></script>
    <script src="<?=JS_DIR?>/include/jquery.validationEngine-ja.js?ver=<?=date('ymdHis')?>"></script>
	<script src="<?=JS_DIR?>/include/slick.min.js"></script>
	<script src="<?=JS_DIR?>/include/perfect-scrollbar.js?ver=<?=date('ymdHis')?>"></script>
    <script src="<?=JS_DIR?>/common/jquery.datatable.js?ver=<?=date('ymdHis')?>"></script>
	<script src="<?=JS_DIR?>/common/functions.js?ver=<?=date('ymdHis')?>"></script>
	<script src="<?=JS_DIR?>/common/message.js?ver=<?=date('ymdHis')?>"></script>
	<script src="<?=JS_DIR?>/common/ajax.js?ver=<?=date('ymdHis')?>"></script>
	<script src="<?=JS_DIR?>/common/jquery.input.controller.js?ver=<?=date('ymdHis')?>"></script>
	<script src="<?=JS_DIR?>/common/master.js?ver=<?=date('ymdHis')?>"></script>
	<script src="<?=JS_DIR?>/common/jquery.common.js?ver=<?=date('ymdHis')?>"></script>
