DROP TABLE IF EXISTS tmp_jgscd_sntcd;
CREATE TEMPORARY TABLE tmp_jgscd_sntcd
SELECT
	JGSCD
,	MAX(JGSNM) AS JGSNM
,	SNTCD
,	MAX(SNTNM) AS SNTNM
FROM
(SELECT JGSCD,JGSNM,SNTCD,SNTNM FROM shipment_confirm_details GROUP BY JGSCD,JGSNM,SNTCD,SNTNM
UNION
SELECT JGSCD,JGSNM,SNTCD,SNTNM FROM shipment_provisional_details GROUP BY JGSCD,JGSNM,SNTCD,SNTNM
UNION
SELECT JGSCD_NK AS JGSCD, JGSNM_NK AS JGSNM, SNTCD_NK AS SNTCD, SNTNM_NK AS SNTNM FROM arrival_schedules GROUP BY JGSCD,JGSNM,SNTCD,SNTNM
UNION
SELECT JGSCD_SK AS JGSCD, JGSNM_SK AS JGSNM, SNTCD_SK AS SNTCD, SNTNM_SK AS SNTNM FROM arrival_schedule_details GROUP BY JGSCD,JGSNM,SNTCD,SNTNM
UNION
SELECT JGSCD,JGSNM,SNTCD,SNTNM FROM location_stocks GROUP BY JGSCD,JGSNM,SNTCD,SNTNM
) AS A
WHERE JGSCD IS NOT NULL AND SNTCD IS NOT NULL AND JGSCD != '' AND SNTCD != ''
GROUP BY JGSCD,SNTCD
ORDER BY JGSCD,SNTCD;


DELETE FROM mtb_center;
DELETE FROM mtb_jigyosho;

INSERT INTO mtb_jigyosho(JGSCD,JGSNM)
SELECT JGSCD,MAX(JGSNM) FROM tmp_jgscd_sntcd GROUP BY JGSCD;

INSERT INTO mtb_center(JGSCD,SNTCD,SNTNM)
SELECT JGSCD,SNTCD,MAX(SNTNM) FROM tmp_jgscd_sntcd GROUP BY JGSCD,SNTCD;

ALTER TABLE mtb_jigyosho ENGINE = InnoDB;
ALTER TABLE mtb_center ENGINE = InnoDB;

SELECT * FROM mtb_jigyosho;
SELECT * FROM mtb_center;
